# -*- coding: utf-8 -*-
"""ch03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWFKRZIKeCKW2GkgBnX_Ku73yqlNswx6
"""

strVal = 'data science'                 #문자열 변수
nVal = 12345                            #정수형 변수
fVal = 1.2                              #실수형 변수
lVal = {'data', 'science'}              #리스트
dVal = {'lecture' : 'data science'}     #딕셔너리 
bVal = True                             #논리형 변수(참/거짓)